import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';

import burgerShop from '@/public/images/burger-shop.jpg';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased relative`}
      >
        <div
          className='absolute inset-0 z-0 bg-cover bg-center filter blur-sm'
          style={{ backgroundImage: `url(${burgerShop.src})` }}
        />

        {/* Overlay for content visibility */}
        <div className='relative z-10'>{children}</div>
      </body>
    </html>
  );
}
